public enum Token {
    IDENT, VAR, INTEGER_ID, FLOAT_ID, LONG_ID, INTEGER_LIT, FLOAT_LIT, LONG_LIT, PLUS, MINUS, MULTI, DIVIDE, MODULO, 
    WHILE, IF, ELSE, START_FILE, END_FILE, ASSIGNMENT, SEMICOLON, LEFT_PARENTHESIS, RIGHT_PARENTHESIS,
    COMMA, DOT, AND, OR, NOT, EQUAL, EQUAL_EQUAL, LESS_OR_EQUALS, GREATER_OR_EQUALS, NOT_EQUALS, 
    GREATER_THAN, LESS_THAN, LEFT_BRACE, RIGHT_BRACE, UNKNOWN;   
}
